# Generated by Django 6.0.5 on 2026-05-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esp_id', models.CharField(blank=True, default='', max_length=100)),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('p_active', models.FloatField()),
                ('p_reactive', models.FloatField()),
                ('p_apparent', models.FloatField()),
                ('power_factor', models.FloatField()),
                ('phase', models.FloatField()),
                ('frequency', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'data_modules',
                'ordering': ['esp_id'],
            },
        ),
    ]
