# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pahomqtt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("icon", models.CharField(blank=True, default="plug", max_length=40)),
                ("status", models.CharField(default="offline", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "Devices",
                "ordering": ["device_id"],
            },
        ),
        migrations.CreateModel(
            name="ESPModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("esp_id", models.CharField(max_length=100, unique=True)),
                ("owner", models.CharField(blank=True, default="", max_length=120)),
            ],
            options={
                "db_table": "ESP_Modules",
                "ordering": ["owner"],
            },
        ),
        migrations.AlterField(
            model_name="messages",
            name="frequency",
            field=models.FloatField(),
        ),
    ]
