# Generated by Django 6.0.5 on 2026-05-27 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pahomqtt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESPModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esp_id', models.CharField(max_length=100, unique=True)),
                ('owner', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='messages',
            name='frequency',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='messages',
            name='esp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pahomqtt.espmodule'),
        ),
    ]
