# Generated by Django 6.0.5 on 2026-05-27 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pahomqtt', '0002_espmodule_alter_messages_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espmodule',
            options={'ordering': ['owner']},
        ),
        migrations.AlterModelTable(
            name='espmodule',
            table='ESP_Modules',
        ),
        migrations.AlterModelTable(
            name='messages',
            table='Sensor_Messages',
        ),
    ]
