# Generated by Codex on 2026-06-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pahomqtt", "0002_device_espmodule_messages_frequency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messages",
            options={"ordering": ["date"]},
        ),
    ]
