# Generated by Django 6.0.5 on 2026-06-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pahomqtt', '0003_alter_espmodule_options_alter_espmodule_table_and_more'),
        ('pahomqtt', '0004_device_owner'),
    ]

    operations = [
    ]
