# Generated by Django 6.0.5 on 2026-06-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pahomqtt', '0005_merge_20260603_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espmodule',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='messages',
            name='esp_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterModelTable(
            name='messages',
            table='data_modules',
        ),
    ]
