# Generated by Django 6.0.5 on 2026-06-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pahomqtt', '0005_usercfesettings'),
        ('pahomqtt', '0006_alter_espmodule_owner_alter_messages_esp_id_and_more'),
    ]

    operations = [
    ]
