# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pahomqtt", "0007_merge_20260604_0334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercfesettings",
            name="rate",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
