import { defineStore } from 'pinia'

const messages = {
  ES: {
    monitor: 'Monitor',
    analytics: 'Análisis',
    admin: 'Administrar',
    profile: 'Perfil',
    total: 'Consumo Total',
    activeDevices: 'dispositivos activos',
    logout: 'Cerrar sesión',
    light: 'Claro',
    dark: 'Oscuro',
    languageSpanish: 'Español',
    languageEnglish: 'English',
    viewProfile: 'Ver perfil',
    account: 'Cuenta',
    monitorTitle: 'Monitor en Tiempo Real',
    monitorSubtitle: 'Monitoreo de consumo eléctrico de dispositivos',
    currentTotal: 'Consumo Total Actual',
    devices: 'Dispositivos',
    of: 'de',
    deviceId: 'ID',
    moreOptions: 'Más opciones',
    lastUpdate: 'Última actualización',
    noData: 'Sin datos',
    online: 'En línea',
    offline: 'Fuera de línea',
    detailLabel: 'Detalle de dispositivo',
    closeDetail: 'Cerrar detalle',
    activePower: 'Potencia Activa',
    reactivePower: 'Potencia Reactiva',
    apparentPower: 'Potencia Aparente',
    powerFactor: 'Factor de Potencia',
    watts: 'Watts',
    electricalParameters: 'Parámetros Eléctricos',
    voltage: 'Voltaje',
    current: 'Corriente',
    phase: 'Fase',
    frequency: 'Frecuencia',
    additionalInfo: 'Información Adicional',
    deviceStatus: 'Estado del dispositivo',
    estimatedDaily: 'Consumo estimado/día',
    frontendConnection: 'Conexión frontend',
    analyticsTitle: 'Análisis',
    analyticsSubtitle: 'Análisis histórico de consumo eléctrico',
    usageHistory: 'Historial de Consumo',
    device: 'Dispositivo',
    allDevices: 'Todos los dispositivos',
    timeRange: 'Rango de tiempo',
    last24h: 'Últimas 24 horas',
    sevenDays: '7 días',
    thirtyDays: '30 días',
    deviceUsage: 'Consumo por Dispositivo',
    generalStats: 'Estadísticas Generales',
    average24h: 'Consumo Promedio (24h)',
    monthlyEstimate: 'Estimado Mensual',
    activeDevicesLabel: 'Dispositivos Activos',
    currentPeriod: 'Este periodo',
    currentTotalUsage: 'Consumo total actual',
    periodAverage: 'Promedio del periodo',
    operatingRange: 'En rango operativo',
    cfeRate: 'Tarifa CFE',
    configuredLimit: 'Límite',
    used: 'usado',
    remaining: 'restantes',
    manageTitle: 'Administrar Dispositivos',
    manageSubtitle: 'Gestiona tus dispositivos de monitoreo',
    addDevice: 'Agregar Dispositivo',
    newDevice: 'Nuevo Dispositivo',
    deviceIdLabel: 'ID del Dispositivo',
    deviceNameLabel: 'Nombre del Dispositivo',
    addDeviceAction: 'Agregar Dispositivo',
    cancel: 'Cancelar',
    status: 'Estado',
    power: 'Potencia',
    actions: 'Acciones',
    updated: 'Actualizado',
    delete: 'Eliminar',
    importantInfo: 'Información importante',
    uniqueIdInfo: 'Cada dispositivo debe tener un ID único para su identificación',
    offlineInfo: 'Los dispositivos aparecerán como "Fuera de línea" hasta que empiecen a enviar datos',
    cooldownInfo: 'La vista respeta un cooldown para no interrumpir altas o eliminaciones',
    profileTitle: 'Perfil',
    profileSubtitle: 'Información general de la cuenta',
    yourProfile: 'Tu Perfil',
    name: 'Nombre',
    email: 'Email',
    deviceCount: 'Número de dispositivos',
    configuredCfeRate: 'Tarifa CFE configurada',
    bimonthlyLimit: 'Límite bimestral',
    createdAt: 'Fecha de creación',
    edit: 'Editar',
    loginHeroTitle: 'Monitorea tu consumo eléctrico en tiempo real',
    loginHeroCopy: 'PowerLytix te permite visualizar, analizar y optimizar el consumo energético de todos tus dispositivos desde un solo lugar.',
    realtimeMonitoring: 'Monitoreo en Tiempo Real',
    realtimeMonitoringCopy: 'Visualiza el consumo instantáneo de cada dispositivo',
    advancedAnalytics: 'Análisis Avanzado',
    advancedAnalyticsCopy: 'Analiza tendencias y patrones de consumo histórico',
    loginFooter: '© 2026 PowerLytix. Sistema de monitoreo eléctrico inteligente.',
    welcomeBack: 'Bienvenido de nuevo',
    credentialsCopy: 'Ingresa tus credenciales para continuar',
    emailLabel: 'Correo electrónico',
    passwordLabel: 'Contraseña',
    signIn: 'Iniciar sesión',
    noAccount: '¿No tienes cuenta? Regístrate aquí',
    missingLogin: 'Ingresa correo y contraseña.',
    registerHeroTitle: 'Gestiona energía con datos claros',
    registerHeroCopy: 'Registra tu cuenta para conectar dispositivos, revisar potencia activa y analizar tu consumo con tarifa CFE.',
    apiReady: 'Preparado para consumir la API REST de Django',
    createAccount: 'Crear cuenta',
    configureAccess: 'Configura tu acceso a PowerLytix',
    confirmation: 'Confirmación',
    register: 'Registrarme',
    hasAccount: 'Ya tengo cuenta',
    completeFields: 'Completa todos los campos.',
    passwordsMismatch: 'Las contraseñas no coinciden.',
    namePlaceholder: 'Tu nombre',
    deviceIdPlaceholder: 'Ej: DEV004',
    deviceNamePlaceholder: 'Ej: Lavadora',
    iconLabel: 'Ícono del dispositivo',
    confirmDeleteTitle: 'Eliminar dispositivo',
    confirmDeleteCopy: 'Esta acción eliminará el dispositivo seleccionado de la lista.',
    keepDevice: 'Conservar',
    iconAir: 'Aire acondicionado',
    iconComputer: 'Computadora',
    iconFridge: 'Refrigerador',
    iconWasher: 'Lavadora',
    iconMicrowave: 'Microondas',
    iconLamp: 'Lámpara',
    iconTv: 'Televisión',
    iconFan: 'Ventilador',
    iconHeater: 'Calefactor',
    iconRouter: 'Router',
    iconPrinter: 'Impresora',
    iconPhone: 'Teléfono',
    iconTablet: 'Tablet',
    iconSpeaker: 'Bocina',
    iconConsole: 'Consola',
    iconCoffee: 'Cafetera',
    iconKitchen: 'Cocina',
    iconBulb: 'Foco',
    iconBattery: 'Batería',
    iconCable: 'Cable',
    iconOutlet: 'Contacto',
    iconPlug: 'General',
    logoTagline: 'Análisis energético',
    registerFooter: '© 2026 PowerLytix.',
    iotPlugin: 'IoT plug-in',
  },
  EN: {
    monitor: 'Monitor',
    analytics: 'Analytics',
    admin: 'Manage',
    profile: 'Profile',
    total: 'Total Usage',
    activeDevices: 'active devices',
    logout: 'Sign out',
    light: 'Light',
    dark: 'Dark',
    languageSpanish: 'Español',
    languageEnglish: 'English',
    viewProfile: 'View profile',
    account: 'Account',
    monitorTitle: 'Real-Time Monitor',
    monitorSubtitle: 'Electrical consumption monitoring for devices',
    currentTotal: 'Current Total Usage',
    devices: 'Devices',
    of: 'of',
    deviceId: 'ID',
    moreOptions: 'More options',
    lastUpdate: 'Last update',
    noData: 'No data',
    online: 'Online',
    offline: 'Offline',
    detailLabel: 'Device detail',
    closeDetail: 'Close detail',
    activePower: 'Active Power',
    reactivePower: 'Reactive Power',
    apparentPower: 'Apparent Power',
    powerFactor: 'Power Factor',
    watts: 'Watts',
    electricalParameters: 'Electrical Parameters',
    voltage: 'Voltage',
    current: 'Current',
    phase: 'Phase',
    frequency: 'Frequency',
    additionalInfo: 'Additional Information',
    deviceStatus: 'Device status',
    estimatedDaily: 'Estimated daily usage',
    frontendConnection: 'Frontend connection',
    analyticsTitle: 'Analytics',
    analyticsSubtitle: 'Historical electrical usage analysis',
    usageHistory: 'Usage History',
    device: 'Device',
    allDevices: 'All devices',
    timeRange: 'Time range',
    last24h: 'Last 24 hours',
    sevenDays: '7 days',
    thirtyDays: '30 days',
    deviceUsage: 'Usage by Device',
    generalStats: 'General Statistics',
    average24h: 'Average Usage (24h)',
    monthlyEstimate: 'Monthly Estimate',
    activeDevicesLabel: 'Active Devices',
    currentPeriod: 'This period',
    currentTotalUsage: 'Current total usage',
    periodAverage: 'Period average',
    operatingRange: 'Within operating range',
    cfeRate: 'CFE Rate',
    configuredLimit: 'Limit',
    used: 'used',
    remaining: 'remaining',
    manageTitle: 'Manage Devices',
    manageSubtitle: 'Manage your monitoring devices',
    addDevice: 'Add Device',
    newDevice: 'New Device',
    deviceIdLabel: 'Device ID',
    deviceNameLabel: 'Device Name',
    addDeviceAction: 'Add Device',
    cancel: 'Cancel',
    status: 'Status',
    power: 'Power',
    actions: 'Actions',
    updated: 'Updated',
    delete: 'Delete',
    importantInfo: 'Important information',
    uniqueIdInfo: 'Each device must have a unique ID for identification',
    offlineInfo: 'Devices will appear as "Offline" until they start sending data',
    cooldownInfo: 'This view respects a cooldown so add/delete actions are not interrupted',
    profileTitle: 'Profile',
    profileSubtitle: 'General account information',
    yourProfile: 'Your Profile',
    name: 'Name',
    email: 'Email',
    deviceCount: 'Number of devices',
    configuredCfeRate: 'Configured CFE rate',
    bimonthlyLimit: 'Bimonthly limit',
    createdAt: 'Created at',
    edit: 'Edit',
    loginHeroTitle: 'Monitor your electrical usage in real time',
    loginHeroCopy: 'PowerLytix helps you visualize, analyze, and optimize energy usage for all your devices in one place.',
    realtimeMonitoring: 'Real-Time Monitoring',
    realtimeMonitoringCopy: 'View instant consumption for each device',
    advancedAnalytics: 'Advanced Analytics',
    advancedAnalyticsCopy: 'Analyze historical usage trends and patterns',
    loginFooter: '© 2026 PowerLytix. Smart electrical monitoring system.',
    welcomeBack: 'Welcome back',
    credentialsCopy: 'Enter your credentials to continue',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    signIn: 'Sign in',
    noAccount: 'No account? Register here',
    missingLogin: 'Enter email and password.',
    registerHeroTitle: 'Manage energy with clear data',
    registerHeroCopy: 'Create your account to connect devices, review active power, and analyze usage with CFE rates.',
    apiReady: 'Ready to consume the Django REST API',
    createAccount: 'Create account',
    configureAccess: 'Set up your PowerLytix access',
    confirmation: 'Confirmation',
    register: 'Register',
    hasAccount: 'I already have an account',
    completeFields: 'Complete all fields.',
    passwordsMismatch: 'Passwords do not match.',
    namePlaceholder: 'Your name',
    deviceIdPlaceholder: 'Ex: DEV004',
    deviceNamePlaceholder: 'Ex: Washer',
    iconLabel: 'Device icon',
    confirmDeleteTitle: 'Delete device',
    confirmDeleteCopy: 'This action will remove the selected device from the list.',
    keepDevice: 'Keep device',
    iconAir: 'Air conditioner',
    iconComputer: 'Computer',
    iconFridge: 'Refrigerator',
    iconWasher: 'Washer',
    iconMicrowave: 'Microwave',
    iconLamp: 'Lamp',
    iconTv: 'Television',
    iconFan: 'Fan',
    iconHeater: 'Heater',
    iconRouter: 'Router',
    iconPrinter: 'Printer',
    iconPhone: 'Phone',
    iconTablet: 'Tablet',
    iconSpeaker: 'Speaker',
    iconConsole: 'Console',
    iconCoffee: 'Coffee maker',
    iconKitchen: 'Kitchen appliance',
    iconBulb: 'Light bulb',
    iconBattery: 'Battery',
    iconCable: 'Cable',
    iconOutlet: 'Outlet',
    iconPlug: 'General',
    logoTagline: 'Energy analytics',
    registerFooter: '© 2026 PowerLytix.',
    iotPlugin: 'IoT plug-in',
  },
}

export const useUiStore = defineStore('ui', {
  state: () => ({
    theme: localStorage.getItem('powerlytix_theme') || 'light',
    language: localStorage.getItem('powerlytix_language') || 'ES',
  }),
  getters: {
    t: (state) => (key) => messages[state.language]?.[key] || messages.ES[key] || key,
  },
  actions: {
    setTheme(theme) {
      this.theme = theme
      localStorage.setItem('powerlytix_theme', theme)
      document.documentElement.dataset.theme = theme
    },
    toggleTheme() {
      this.setTheme(this.theme === 'light' ? 'dark' : 'light')
    },
    setLanguage(language) {
      this.language = language
      localStorage.setItem('powerlytix_language', language)
    },
    hydrate() {
      document.documentElement.dataset.theme = this.theme
    },
  },
})
